### ISSUE TITLE
Duplicate module named react-native

### ISSUE THREAD

**Issue by massivespace** [GoldenOwlAsia/react-native-twitter-signin#117]
After I install this module into my existing React Native application, I get an error on startup (on iOS currently, have not checked Android).  In the simulator, it says "Metro bundler has encountered an internal error, please check your terminal...  In the term window, it says:
Loading dependency graph...(node:72780) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/me/WebstormProjects/my_app/node_modules/react-native-twitter-signin/node_modules/react-native/package.json collides with /Users/me/WebstormProjects/my_app/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/me/WebstormProjects/my_app/node_modules/metro/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/me/WebstormProjects/my_app/node_modules/metro/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Is there a way to prevent this module from downloading react-native (and several others it appears) and use the existing version in my node_modules directory?

**Comment by LiuZhe1** [comment]
Yes, I am also faced about this issue.

**Comment by amit00978** [comment]
I have the same issue

**Comment by mahmoudfelfel** [comment]
had to rollback to `react-native-twitter-signin@1.0.2` then run `react-native start --resetCache` for it to work again

**Comment by khalidos32** [comment]
I faced the same issue... here is my solution:
I changed the version of react and react native used by the (react-native-twitter-signin) package manually from Package-look. Jason after that I did the same on the node_module/react-native-twitter... /package. json and I deleted the react-native modules at the same path. This solution worked for me.

**Comment by recepkocur** [comment]
I have the same issue +1

**Comment by namlongsoft** [comment]
I have to remove folder **react-native** inside react-native-twitter-signin/node_modules and then **npm start  -- --reset-cache**. It works for me.

**Comment by hArsh92** [comment]
Do we have a work around for this?

**Comment by furrutiaunicode** [comment]
this was fixed, but the version of the npm has not been updated, here in github this is the last version running and it was changed in the package.json the dependencies, before it requested to use react and native-reactive, and now it does not request both. So it was corrected. regards

Fix:
Download the latest version from github to fix this error. (Do not use npm, until the author updates the version uploaded on the web)

**Comment by furrutiaunicode** [comment]
> Do we have a work around for this?

this was fixed, but the version of the npm has not been updated, here in github this is the last version running and it was changed in the package.json the dependencies, before it requested to use react and native-reactive, and now it does not request both. So it was corrected. regards

Fix:
Download the latest version from github to fix this error. (Do not use npm, until the author updates the version uploaded on the web)

**Comment by LonelyCpp** [comment]
I fixed this by removing the dependencies in the node module

1. edit `node_modules/react-native-twitter-signin/package.json` and remove the lines 
```
"react": "^16.4.1",
"react-native": "^0.56.0"
```

2. delete the `react-native` folder in `node_modules/react-native-twitter-signin/node_modules`
(note: this is the `node_modules` folder **inside** `react-native-twitter-signin`)

3. re run `react-native run-android` (or run-ios)

**Comment by hArsh92** [comment]
> Do we have a work around for this?

If you see `master` branch, it already has the fix. So I just had to run this command and the error is gone.

`npm install --save GoldenOwlAsia/react-native-twitter-signin#master`

I think this issue is because the version of `npm` is not updated.

**Comment by cdra0624** [comment]
you have to wait this PR
https://github.com/GoldenOwlAsia/react-native-twitter-signin/pull/120

or run post install script

`postinstall: rm -rf node_modules/react-native-twitter-signin/node_modules/react-native`

**Comment by thepolygongo** [comment]
I solved this issue.
https://stackoverflow.com/questions/52320203/react-native-twitter-signin-release-build-issue/52757420#52757420

**Comment by mustafamagdy** [comment]
Will this be fixed soon, it is tedious to remove the react-native directory on each install, why this is an issue in the first place?

**Comment by webmasterdragon** [comment]
Did it fixed? I have same issue now.

**Comment by cloudy-ninja** [comment]
I faced this issue.

**Comment by tkaplan9** [comment]
why haven't this issue still haven't fixed it's annoying to manually delete that folder every time I install a new library

**Comment by franznkemaka** [comment]
Hi Developers,
For those who are on Windows, here is a small batch file which you will have to run every time you use 
`npm install`

1. Edit the package.json of react-native-twitter-signin and remove react-native from the dependencies.
2. Copy it to your project root folder, rename it to react-native-twitter-signin.json for example
3. Create this batch file

**autofix.bat**
```
del "node_modules\react-native-twitter-signin\package.json"
@RD /S /Q "node_modules\react-native-twitter-signin\node_modules\react-native"
copy react-native-twitter-signin.json node_modules\react-native-twitter-signin\package.json
```
4. Just hit `autofix` in your project root folder.

Hope this will help!
Franz

**Comment by km-tr** [comment]
Will you release a new version because it seems to work if master?
