### ISSUE TITLE
No 'main' module

### ISSUE THREAD

**Issue by danielfein** [GoldenOwlAsia/react-native-twitter-signin#139]
I've installed and linked the repo, and the code builds successfully but when importing it I'm met with an error indicating there's no main module. This is likely due to no index.js or similar file for the import to land on.

This is the error:

```
error: bundling failed: Error: While trying to resolve module `react-native-twitter-signin` from file `/Users/danfein/Desktop/native/components/Authentication/index.js`, the package `/Users/danfein/Desktop/native/node_modules/react-native-twitter-signin/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/danfein/Desktop/native/node_modules/react-native-twitter-signin/index`. Indeed, none of these files exist:

  * `/Users/danfein/Desktop/native/node_modules/react-native-twitter-signin/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/danfein/Desktop/native/node_modules/react-native-twitter-signin/index/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/danfein/Desktop/native/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
```

Any ideas to remediate?

**Comment by danielfein** [comment]
Resolved by removing node_modules and running npm install, and then closing metro and reopening.
